-- Users authenticated via Google OAuth. We store the minimum we need for
-- display (name, avatar) and the canonical Google `sub` claim, which is
-- the stable opaque user id Google guarantees.

CREATE TABLE users (
  id text PRIMARY KEY,                          -- ULID, generated by api
  email text UNIQUE NOT NULL,
  name text NOT NULL,
  avatar_url text,
  google_sub text UNIQUE NOT NULL,              -- "sub" claim from Google id_token
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX users_email_idx ON users (lower(email));
